version: '3.8'
networks:
    app-network:
        driver: bridge
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  todoapp:
    image: todoapp_image:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoapp
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
volumes:
    mysql_data: {}